// Generated by gencpp from file ian_gregory_roslab/scan_range.msg
// DO NOT EDIT!


#ifndef IAN_GREGORY_ROSLAB_MESSAGE_SCAN_RANGE_H
#define IAN_GREGORY_ROSLAB_MESSAGE_SCAN_RANGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ian_gregory_roslab
{
template <class ContainerAllocator>
struct scan_range_
{
  typedef scan_range_<ContainerAllocator> Type;

  scan_range_()
    : header()
    , range_min(0.0)
    , range_max(0.0)
    , angle_min(0.0)
    , angle_max(0.0)  {
    }
  scan_range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , range_min(0.0)
    , range_max(0.0)
    , angle_min(0.0)
    , angle_max(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _range_min_type;
  _range_min_type range_min;

   typedef float _range_max_type;
  _range_max_type range_max;

   typedef float _angle_min_type;
  _angle_min_type angle_min;

   typedef float _angle_max_type;
  _angle_max_type angle_max;





  typedef boost::shared_ptr< ::ian_gregory_roslab::scan_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ian_gregory_roslab::scan_range_<ContainerAllocator> const> ConstPtr;

}; // struct scan_range_

typedef ::ian_gregory_roslab::scan_range_<std::allocator<void> > scan_range;

typedef boost::shared_ptr< ::ian_gregory_roslab::scan_range > scan_rangePtr;
typedef boost::shared_ptr< ::ian_gregory_roslab::scan_range const> scan_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ian_gregory_roslab::scan_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ian_gregory_roslab::scan_range_<ContainerAllocator1> & lhs, const ::ian_gregory_roslab::scan_range_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.range_min == rhs.range_min &&
    lhs.range_max == rhs.range_max &&
    lhs.angle_min == rhs.angle_min &&
    lhs.angle_max == rhs.angle_max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ian_gregory_roslab::scan_range_<ContainerAllocator1> & lhs, const ::ian_gregory_roslab::scan_range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ian_gregory_roslab

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ian_gregory_roslab::scan_range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ian_gregory_roslab::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ian_gregory_roslab::scan_range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aada86769d7aab743bbb3d0fa41ba261";
  }

  static const char* value(const ::ian_gregory_roslab::scan_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaada86769d7aab74ULL;
  static const uint64_t static_value2 = 0x3bbb3d0fa41ba261ULL;
};

template<class ContainerAllocator>
struct DataType< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ian_gregory_roslab/scan_range";
  }

  static const char* value(const ::ian_gregory_roslab::scan_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 range_min\n"
"float32 range_max\n"
"float32 angle_min\n"
"float32 angle_max\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ian_gregory_roslab::scan_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.range_min);
      stream.next(m.range_max);
      stream.next(m.angle_min);
      stream.next(m.angle_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scan_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ian_gregory_roslab::scan_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ian_gregory_roslab::scan_range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range_min: ";
    Printer<float>::stream(s, indent + "  ", v.range_min);
    s << indent << "range_max: ";
    Printer<float>::stream(s, indent + "  ", v.range_max);
    s << indent << "angle_min: ";
    Printer<float>::stream(s, indent + "  ", v.angle_min);
    s << indent << "angle_max: ";
    Printer<float>::stream(s, indent + "  ", v.angle_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAN_GREGORY_ROSLAB_MESSAGE_SCAN_RANGE_H
